### PR TITLE
Derive keyguard origin from config.keyguardSrc

### PR DESCRIPTION
**Pull request by sisou**
Add the keystoreOrigin as a paramter

### CODE REVIEW

**Review by Bettelstab — CHANGES_REQUESTED** [review]
I think we don't need to specify the target origin. Why? Because it's us initializing the connection and we are talking with the trusted keyguard. The only malicious thing which could happen is: An attacker changes the window location to another origin under his control, so we think he is the keyguard. But to do so, he needs control over 
a) the keyguard => no improvement
b) us => no improvement
So I conclude we don't need this parameter.
However, the other minor fixes are very welcome ;)

**Review by Bettelstab — CHANGES_REQUESTED** [review]
I think we don't need to specify the target origin. Why? Because it's us initializing the connection and we are talking with the trusted keyguard. The only malicious thing which could happen is: An attacker changes the window location to another origin under his control, so we think he is the keyguard. But to do so, he needs control over 
a) the keyguard => no improvement
b) us => no improvement
So I conclude we don't need this parameter.
However, the other minor fixes are very welcome ;)

**Review by Bettelstab — DISMISSED** [review]
I think we don't need to specify the target origin. Why? Because it's us initializing the connection and we are talking with the trusted keyguard. The only malicious thing which could happen is: An attacker changes the window location to another origin under his control, so we think he is the keyguard. But to do so, he needs control over 
a) the keyguard => no improvement
b) us => no improvement
So I conclude we don't need this parameter.
However, the other minor fixes are very welcome ;)

**Comment by sisou** [comment]
It is generally considered *best practice* to always specify the target origin, if it is known. See this excerpt from MDN:
> Always provide a specific targetOrigin, not *, if you know where the other window's document should be located. Failing to provide a specific target discloses the data you send to any interested malicious site. (https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)

And because we _know_, that the keyguard-client will ONLY EVER communicate with the keyguard page, we should really specifiy the targetOrigin, as to not leak ANY user info to a third party. Because changing the location of an iframe or popup is not bound to the same-origin policy, only reading the location. Thus any browser-extension or otherwise third-party could change the href of the iframe without the user noticing, thus the user sending requests, e.g. for transactions to be signed, or their PIN, into the third-party iframe.

Since we cannot hard-code the targetOrigin in the keyguard-client, because we also need devOptions, this needs to be an optional parameter during initialization, which it is in this PR.

I vote for the targetOrigin parameter to stay.

**Comment by styppo** [comment]
It certainly doesn't hurt to lock the RPC requests to a specific target origin (it does help in some corner cases, e.g. the user actively navigating the popup window). I would however derive the origin from the `src` parameter instead of having a separate parameter for it. I don't see any realistic use cases where these two origins would be different.

**Pull request merged**
